services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/sbs
      - SPRING_DATASOURCE_USERNAME=unijuni
      - SPRING_DATASOURCE_PASSWORD=heejun0109
    depends_on:
      - mysql
    networks:
      - sbs-network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=sbs
      - MYSQL_USER=unijuni
      - MYSQL_PASSWORD=heejun0109
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - sbs-network

networks:
  sbs-network:
    driver: bridge

volumes:
  mysql-data: