# Blue 환경용 앱 컨테이너 Compose 파일
services:
  app-blue:
    image: unijuni/artium:latest
    container_name: artium-app-blue
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${PROFILE:-dev}
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
    command: ["java", "-jar", "app.jar"]
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - artium-network
    restart: unless-stopped

networks:
  artium-network:
    external: false